const SPAIN_CITIES = [
  'Alava',
  'Albacete',
  'Alicante',
  'Almeria',
  'Asturias',
  'Avila',
  'Badajoz',
  'Barcelona',
  'Burgos',
  'Caceres',
  'Cadiz',
  'Cantabria',
  'Castellon',
  'Ciudad Real',
  'Cordoba',
  'Coruna',
  'Cuenca',
  'El Hierro',
  'Formentera',
  'Fuertaventura',
  'Gerona',
  'Gran Canaria',
  'Granada',
  'Guadalajara',
  'Guipuzcoa',
  'Huelva',
  'Huesca',
  'Ibiza',
  'Jaen',
  'La Palma',
  'La Rioja',
  'Lanzarote',
  'Leon',
  'Lerida',
  'Lugo',
  'Madrid',
  'Malaga',
  'Mallorca',
  'Menorca',
  'Murcia',
  'Navarra',
  'Orense',
  'Palencia',
  'Pontevedra',
  'Salamanca',
  'Segovia',
  'Sevilla',
  'Soria',
  'Tarragona',
  'Tenerife',
  'Teruel',
  'Toledo',
  'Valencia',
  'Valladolid',
  'Vizcaya',
  'Zamora',
  'Zaragoza',
];

const PORTUGAL_CITIES = [
  'Aveiro',
  'Beja',
  'Braga',
  'Braganca',
  'Castelo Branco',
  'Coimbra',
  'Corvo',
  'Evora',
  'Faial',
  'Faro',
  'Flores',
  'Graciosa',
  'Guarda',
  'Leiria',
  'Lisbon',
  'Madeira',
  'Pico',
  'Portalegre',
  'Porto',
  'Santa Maria',
  'Santarem',
  'Sao Jorge',
  'Sao Miguel',
  'Setubal',
  'Terceira',
  'Viana do Castelo',
  'Vila Real',
  'Viseu',
];

const ITALY_CITIES = [
  'Agrigento',
  'Alessandria',
  'Ancona',
  'Aosta Valley',
  'Arezzo',
  'Ascoli Piceno',
  'Asti',
  'Avelino province',
  'Bari',
  'Barletta-Andria-Trani',
  'Belluno',
  'Benevento',
  'Bergamo',
  'Biella',
  'Bologna',
  'Brescia',
  'Brindisi',
  'Cagliari',
  'Caltanissetta',
  'Campobasso',
  'Caserta',
  'Catania',
  'Catanzaro',
  'Chieti',
  'Como',
  'Cosenza',
  'Cremona',
  'Crotone',
  'Cuneo',
  'Enna',
  'Fermo',
  'Ferrara',
  'Florence',
  'Foggia',
  'Forli-Cesena',
  'Frosinone',
  'Genoa',
  'Gorizia',
  'Grosseto',
  'Imperia',
  'Isernia',
  "L'Aquila",
  'La Spezia',
  'Latina',
  'Lecce',
  'Lecco',
  'Livorno',
  'Lodi',
  'Lucca',
  'Macerata',
  'Mantua',
  'Massa and Carrara',
  'Matera',
  'Messina',
  'Milan',
  'Modena',
  'Monza and Brianza',
  'Naples',
  'Novara',
  'Nuoro',
  'Olbia Tempio',
  'Oristano',
  'Padua',
  'Palermo',
  'Parma',
  'Pavia',
  'Perugia',
  'Pesaro and Urbino',
  'Pescara',
  'Piacenza',
  'Pisa',
  'Pistoia',
  'Pordenone',
  'Potenza',
  'Prato',
  'Ragusa',
  'Ravenna',
  'Reggio Calabria',
  'Reggio Emilia',
  'Rieti',
  'Rimini',
  'Rome',
  'Rovigo',
  'Salerno',
  'Sassari',
  'Savona',
  'Siena',
  'Siracusa',
  'Sondrio',
  'South Sardinia',
  'South Tyrol',
  'Sud Sardegna',
  'Taranto',
  'Teramo',
  'Trapani',
  'Trento',
  'Treviso',
  'Trieste',
  'Turin',
  'Udine',
  'Varese',
  'Venice',
  'Verbano Cusio Ossola',
  'Vercelli',
  'Verona',
  'Vibo Valentia',
  'Vicenza',
  'Viterbo',
];

const FRANCE_CITIES = [
  'Ain',
  'Aisne',
  'Allier',
  'Alpes-de-Haute-Provence',
  'Alpes-Maritimes',
  'Ardeche',
  'Ardennes',
  'Ariege',
  'Aube',
  'Aude',
  'Aveyron',
  'Bas-Rhin',
  'Bouches-du-Rhone',
  'Calvados',
  'Cantal',
  'Charente',
  'Charente-Maritime',
  'Cher',
  'Correze',
  'Corse-du-Sud',
  "Cote-d'Or",
  "Cotes-d'Armor",
  'Creuse',
  'Deux-Sevres',
  'Dordogne',
  'Doubs',
  'Drome',
  'Essonne',
  'Eure',
  'Eure-et-Loir',
  'Finistere',
  'French Guiana',
  'Gard',
  'Gers',
  'Gironde',
  'Guadeloupe',
  'Haut-Rhin',
  'Haute-Corse',
  'Haute-Garonne',
  'Haute-Loire',
  'Haute-Marne',
  'Haute-Saone',
  'Haute-Savoie',
  'Haute-Vienne',
  'Hautes-Alpes',
  'Hautes-Pyrenees',
  'Hauts-de-Seine',
  'Herault',
  'Ille-et-Vilaine',
  'Indre',
  'Indre-et-Loire',
  'Isere',
  'Jura',
  'La Reunion',
  'Landes',
  'Loir-et-Cher',
  'Loire',
  'Loire-Atlantique',
  'Loiret',
  'Lot',
  'Lot-et-Garonne',
  'Lozere',
  'Maine-et-Loire',
  'Manche',
  'Marne',
  'Martinique',
  'Mayenne',
  'Meurthe-et-Moselle',
  'Meuse',
  'Morbihan',
  'Moselle',
  'Nievre',
  'Nord',
  'Oise',
  'Orne',
  'Paris',
  'Pas-de-Calais',
  'Puy-de-Dome',
  'Pyrenees-Atlantiques',
  'Pyrenees-Orientales',
  'Rhone',
  'Saint-Martin',
  'Saone-et-Loire',
  'Sarthe',
  'Savoie',
  'Seine-et-Marne',
  'Seine-Maritime',
  'Seine-Saint-Denis',
  'Somme',
  'Tarn',
  'Tarn-et-Garonne',
  'Territoire de Belfort',
  "Val-d'Oise",
  'Val-de-Marne',
  'Var',
  'Vaucluse',
  'Vendee',
  'Vienne',
  'Vosges',
  'Yonne',
  'Yvelines',
];

const COUNTRIES: Record<string, string[]> = {
  spain: SPAIN_CITIES,
  italy: ITALY_CITIES,
  portugal: PORTUGAL_CITIES,
  france: FRANCE_CITIES,
};

export const mapCitiesToOptions = (name: string) => {
  const country = COUNTRIES[name];

  return country.map((city) => ({
    label: city,
    value: city,
  }));
};

export const PROPERTIES_NUMBER = [
  { value: '5-50', label: '5-50' },
  { value: '50-100', label: '50-100' },
  { value: '100-200', label: '100-200' },
  { value: '200-500', label: '200-500' },
  { value: '500-1000', label: '500-1000' },
];

export const TIME_TO_CALL = [
  {
    value: 'Morning',
    label: 'contact.form.date.morning',
  },
  {
    value: 'Afternoon',
    label: 'contact.form.date.afternoon',
  },
];

export const GET_IN_TOUCH = [
  {
    value: 'Email',
    label: 'contact.form.get_in_touch.email',
  },
  {
    value: 'Phone call',
    label: 'contact.form.get_in_touch.phone_call',
  },
];
