FROM node:16-bullseye-slim as base

ENV NODE_ENV development

# add turborepo
RUN npm install --global turbo

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY  ["package-lock.json", "package.json", "./"]  /usr/src/app/

# Copy source files
COPY . /usr/src/app

# Install app dependencies
RUN npm install

COPY docker.dev/npm-package-update /usr/local/bin/
ENTRYPOINT ["npm-package-update"]

# Ports
# 3000 - join(nextjs)
EXPOSE 3000

CMD ["npm", "run", "dev:join"]